# napari hub configuration
# See https://github.com/chanzuckerberg/napari-hub/wiki

project_site: https://github.com/royerlab/napari-chatgpt/wiki

labels:
  ontology:
    - Image processing
    - Image segmentation
    - Visualisation
